name: simple_server
description: >
  Wrappes the dart.io HTTPServer and provides an simple API
  to manage incomming calls. uses the route_provider package
version: 0.2.0
author: Robert Beyer <4sternrb@googlemail.com>
homepage: https://github.com/4stern/SimpleServer
dependencies:
    dart_config: ">=0.5.0 <0.6.0"
    route_provider: ">=0.2.0 < 0.4.0"
